site_name: GoDB Documentation
use_directory_urls: false
nav:
  - Home: index.md
  - Endpoints: ep/index.md
  - Transaction Control: transaction.md
  - SQL Commands:
    - Queries: sql/queries.md
    - DML: sql/dml.md
    - DDL: sql/ddl.md
  - Error Codes: err/index.md
theme: readthedocs