package sql

import "github.com/djbckr/godb/sql/dml"

type Command struct {
}

const (
	// queries
	select_ = "SELECT"
	with_   = "WITH"
	from_   = "FROM"

	// dml
	insert_ = "INSERT"
	update_ = "UPDATE"
	merge_  = "MERGE"
	upsert_ = "UPSERT"
	delete_ = "DELETE"

	// transaction control
	commit_    = "COMMIT"
	rollback_  = "ROLLBACK"
	savepoint_ = "SAVEPOINT"

	// ddl
	alter_  = "ALTER"
	create_ = "CREATE"
	drop_   = "DROP"
	grant_  = "GRANT"
	revoke_ = "REVOKE"
	set_    = "SET"

	// ddl secondary commands
	database_    = "DATABASE"
	index_       = "INDEX"
	sequence_    = "SEQUENCE"
	session_     = "SESSION"
	system_      = "SYSTEM"
	table_       = "TABLE"
	tablespace_  = "TABLESPACE"
	trigger_     = "TRIGGER"
	user_        = "USER"
	view_        = "VIEW"
	controlfile_ = "CONTROLFILE"
	function_    = "FUNCTION"
	role_        = "ROLE"
	schema_      = "SCHEMA"
	synonym_     = "SYNONYM"
	constraint_  = "CONSTRAINT"
	transaction_ = "TRANSACTION"

	// ANSI keywords
	all_       = "ALL"
	and_       = "AND"
	any_       = "ANY"
	as_        = "AS"
	between_   = "BETWEEN"
	by_        = "BY"
	char_      = "CHAR"
	check_     = "CHECK"
	column_    = "COLUMN"
	connect_   = "CONNECT"
	current_   = "CURRENT"
	date_      = "DATE"
	decimal_   = "DECIMAL"
	default_   = "DEFAULT"
	distinct_  = "DISTINCT"
	else_      = "ELSE"
	exists_    = "EXISTS"
	float_     = "FLOAT"
	for_       = "FOR"
	group_     = "GROUP"
	having_    = "HAVING"
	in_        = "IN"
	integer_   = "INTEGER"
	intersect_ = "INTERSECT"
	into_      = "INTO"
	is_        = "IS"
	like_      = "LIKE"
	not_       = "NOT"
	null_      = "NULL"
	of_        = "OF"
	on_        = "ON"
	or_        = "OR"
	order_     = "ORDER"
	row_       = "ROW"
	rows_      = "ROWS"
	smallint_  = "SMALLINT"
	start_     = "START"
	then_      = "THEN"
	to_        = "TO"
	union_     = "UNION"
	unique_    = "UNIQUE"
	values_    = "VALUES"
	varchar_   = "VARCHAR"
	whenever_  = "WHENEVER"
	where_     = "WHERE"

	// other keywords
	access_     = "ACCESS"
	add_        = "ADD"
	asc_        = "ASC"
	audit_      = "AUDIT"
	cluster_    = "CLUSTER"
	comment_    = "COMMENT"
	compress_   = "COMPRESS"
	desc_       = "DESC"
	exclusive_  = "EXCLUSIVE"
	explain_    = "EXPLAIN"
	file_       = "FILE"
	identified_ = "IDENTIFIED"
	immediate_  = "IMMEDIATE"
	increment_  = "INCREMENT"
	initial_    = "INITIAL"
	level_      = "LEVEL"
	lock_       = "LOCK"
	long_       = "LONG"
	maxextents_ = "MAXEXTENTS"
	minus_      = "MINUS"
	mlslabel_   = "MLSLABEL"
	mode_       = "MODE"
	modify_     = "MODIFY"
	noaudit_    = "NOAUDIT"
	nocompress_ = "NOCOMPRESS"
	nowait_     = "NOWAIT"
	number_     = "NUMBER"
	offline_    = "OFFLINE"
	online_     = "ONLINE"
	option_     = "OPTION"
	pctfree_    = "PCTFREE"
	prior_      = "PRIOR"
	privileges_ = "PRIVILEGES"
	public_     = "PUBLIC"
	raw_        = "RAW"
	rename_     = "RENAME"
	resource_   = "RESOURCE"
	rowid_      = "ROWID"
	rownum_     = "ROWNUM"
	share_      = "SHARE"
	size_       = "SIZE"
	successful_ = "SUCCESSFUL"
	sysdate_    = "SYSDATE"
	uid_        = "UID"
	validate_   = "VALIDATE"
	varchar2_   = "VARCHAR2"

	// SQL 2011 reserved words
	abs_                              = "ABS"
	allocate_                         = "ALLOCATE"
	are_                              = "ARE"
	array_                            = "ARRAY"
	array_agg_                        = "ARRAY_AGG"
	array_max_cardinality_            = "ARRAY_MAX_CARDINALITY"
	asensitive_                       = "ASENSITIVE"
	asymmetric_                       = "ASYMMETRIC"
	at_                               = "AT"
	atomic_                           = "ATOMIC"
	authorization_                    = "AUTHORIZATION"
	avg_                              = "AVG"
	begin_                            = "BEGIN"
	begin_frame_                      = "BEGIN_FRAME"
	begin_partition_                  = "BEGIN_PARTITION"
	bigint_                           = "BIGINT"
	binary_                           = "BINARY"
	blob_                             = "BLOB"
	boolean_                          = "BOOLEAN"
	both_                             = "BOTH"
	call_                             = "CALL"
	called_                           = "CALLED"
	cardinality_                      = "CARDINALITY"
	cascaded_                         = "CASCADED"
	case_                             = "CASE"
	cast_                             = "CAST"
	ceil_                             = "CEIL"
	ceiling_                          = "CEILING"
	character_                        = "CHARACTER"
	character_length_                 = "CHARACTER_LENGTH"
	char_length_                      = "CHAR_LENGTH"
	clob_                             = "CLOB"
	close_                            = "CLOSE"
	coalesce_                         = "COALESCE"
	collate_                          = "COLLATE"
	collect_                          = "COLLECT"
	condition_                        = "CONDITION"
	contains_                         = "CONTAINS"
	convert_                          = "CONVERT"
	corr_                             = "CORR"
	corresponding_                    = "CORRESPONDING"
	count_                            = "COUNT"
	covar_pop_                        = "COVAR_POP"
	covar_samp_                       = "COVAR_SAMP"
	cross_                            = "CROSS"
	cube_                             = "CUBE"
	cume_dist_                        = "CUME_DIST"
	current_catalog_                  = "CURRENT_CATALOG"
	current_date_                     = "CURRENT_DATE"
	current_default_transform_group_  = "CURRENT_DEFAULT_TRANSFORM_GROUP"
	current_path_                     = "CURRENT_PATH"
	current_role_                     = "CURRENT_ROLE"
	current_row_                      = "CURRENT_ROW"
	current_schema_                   = "CURRENT_SCHEMA"
	current_time_                     = "CURRENT_TIME"
	current_timestamp_                = "CURRENT_TIMESTAMP"
	current_transform_group_for_type_ = "CURRENT_TRANSFORM_GROUP_FOR_TYPE"
	current_user_                     = "CURRENT_USER"
	cursor_                           = "CURSOR"
	cycle_                            = "CYCLE"
	datalink_                         = "DATALINK"
	day_                              = "DAY"
	deallocate_                       = "DEALLOCATE"
	dec_                              = "DEC"
	declare_                          = "DECLARE"
	dense_rank_                       = "DENSE_RANK"
	deref_                            = "DEREF"
	describe_                         = "DESCRIBE"
	deterministic_                    = "DETERMINISTIC"
	disconnect_                       = "DISCONNECT"
	dlnewcopy_                        = "DLNEWCOPY"
	dlpreviouscopy_                   = "DLPREVIOUSCOPY"
	dlurlcomplete_                    = "DLURLCOMPLETE"
	dlurlcompleteonly_                = "DLURLCOMPLETEONLY"
	dlurlcompletewrite_               = "DLURLCOMPLETEWRITE"
	dlurlpath_                        = "DLURLPATH"
	dlurlpathonly_                    = "DLURLPATHONLY"
	dlurlpathwrite_                   = "DLURLPATHWRITE"
	dlurlscheme_                      = "DLURLSCHEME"
	dlurlserver_                      = "DLURLSERVER"
	dlvalue_                          = "DLVALUE"
	double_                           = "DOUBLE"
	dynamic_                          = "DYNAMIC"
	each_                             = "EACH"
	element_                          = "ELEMENT"
	end_                              = "END"
	end_frame_                        = "END_FRAME"
	end_partition_                    = "END_PARTITION"
	equals_                           = "EQUALS"
	escape_                           = "ESCAPE"
	every_                            = "EVERY"
	except_                           = "EXCEPT"
	exec_                             = "EXEC"
	execute_                          = "EXECUTE"
	exp_                              = "EXP"
	external_                         = "EXTERNAL"
	extract_                          = "EXTRACT"
	false_                            = "FALSE"
	fetch_                            = "FETCH"
	filter_                           = "FILTER"
	first_value_                      = "FIRST_VALUE"
	floor_                            = "FLOOR"
	foreign_                          = "FOREIGN"
	frame_row_                        = "FRAME_ROW"
	free_                             = "FREE"
	full_                             = "FULL"
	fusion_                           = "FUSION"
	get_                              = "GET"
	global_                           = "GLOBAL"
	grouping_                         = "GROUPING"
	groups_                           = "GROUPS"
	hold_                             = "HOLD"
	hour_                             = "HOUR"
	identity_                         = "IDENTITY"
	import_                           = "IMPORT"
	indicator_                        = "INDICATOR"
	inner_                            = "INNER"
	inout_                            = "INOUT"
	insensitive_                      = "INSENSITIVE"
	int_                              = "INT"
	intersection_                     = "INTERSECTION"
	interval_                         = "INTERVAL"
	join_                             = "JOIN"
	lag_                              = "LAG"
	language_                         = "LANGUAGE"
	large_                            = "LARGE"
	last_value_                       = "LAST_VALUE"
	lateral_                          = "LATERAL"
	lead_                             = "LEAD"
	leading_                          = "LEADING"
	left_                             = "LEFT"
	like_regex_                       = "LIKE_REGEX"
	ln_                               = "LN"
	local_                            = "LOCAL"
	localtime_                        = "LOCALTIME"
	localtimestamp_                   = "LOCALTIMESTAMP"
	lower_                            = "LOWER"
	match_                            = "MATCH"
	max_                              = "MAX"
	member_                           = "MEMBER"
	method_                           = "METHOD"
	min_                              = "MIN"
	minute_                           = "MINUTE"
	mod_                              = "MOD"
	modifies_                         = "MODIFIES"
	module_                           = "MODULE"
	month_                            = "MONTH"
	multiset_                         = "MULTISET"
	national_                         = "NATIONAL"
	natural_                          = "NATURAL"
	nchar_                            = "NCHAR"
	nclob_                            = "NCLOB"
	new_                              = "NEW"
	no_                               = "NO"
	none_                             = "NONE"
	normalize_                        = "NORMALIZE"
	nth_value_                        = "NTH_VALUE"
	ntile_                            = "NTILE"
	nullif_                           = "NULLIF"
	numeric_                          = "NUMERIC"
	occurrences_regex_                = "OCCURRENCES_REGEX"
	octet_length_                     = "OCTET_LENGTH"
	offset_                           = "OFFSET"
	old_                              = "OLD"
	only_                             = "ONLY"
	open_                             = "OPEN"
	out_                              = "OUT"
	outer_                            = "OUTER"
	over_                             = "OVER"
	overlaps_                         = "OVERLAPS"
	overlay_                          = "OVERLAY"
	parameter_                        = "PARAMETER"
	partition_                        = "PARTITION"
	percent_                          = "PERCENT"
	percentile_cont_                  = "PERCENTILE_CONT"
	percentile_disc_                  = "PERCENTILE_DISC"
	percent_rank_                     = "PERCENT_RANK"
	period_                           = "PERIOD"
	portion_                          = "PORTION"
	position_                         = "POSITION"
	position_regex_                   = "POSITION_REGEX"
	power_                            = "POWER"
	precedes_                         = "PRECEDES"
	precision_                        = "PRECISION"
	prepare_                          = "PREPARE"
	primary_                          = "PRIMARY"
	procedure_                        = "PROCEDURE"
	range_                            = "RANGE"
	rank_                             = "RANK"
	reads_                            = "READS"
	real_                             = "REAL"
	recursive_                        = "RECURSIVE"
	ref_                              = "REF"
	references_                       = "REFERENCES"
	referencing_                      = "REFERENCING"
	regr_avgx_                        = "REGR_AVGX"
	regr_avgy_                        = "REGR_AVGY"
	regr_count_                       = "REGR_COUNT"
	regr_intercept_                   = "REGR_INTERCEPT"
	regr_r2_                          = "REGR_R2"
	regr_slope_                       = "REGR_SLOPE"
	regr_sxx_                         = "REGR_SXX"
	regr_sxy_                         = "REGR_SXY"
	regr_syy_                         = "REGR_SYY"
	release_                          = "RELEASE"
	result_                           = "RESULT"
	return_                           = "RETURN"
	returns_                          = "RETURNS"
	right_                            = "RIGHT"
	rollup_                           = "ROLLUP"
	row_number_                       = "ROW_NUMBER"
	scope_                            = "SCOPE"
	scroll_                           = "SCROLL"
	search_                           = "SEARCH"
	second_                           = "SECOND"
	sensitive_                        = "SENSITIVE"
	session_user_                     = "SESSION_USER"
	similar_                          = "SIMILAR"
	some_                             = "SOME"
	specific_                         = "SPECIFIC"
	specifictype_                     = "SPECIFICTYPE"
	sql_                              = "SQL"
	sqlexception_                     = "SQLEXCEPTION"
	sqlstate_                         = "SQLSTATE"
	sqlwarning_                       = "SQLWARNING"
	sqrt_                             = "SQRT"
	static_                           = "STATIC"
	stddev_pop_                       = "STDDEV_POP"
	stddev_samp_                      = "STDDEV_SAMP"
	submultiset_                      = "SUBMULTISET"
	substring_                        = "SUBSTRING"
	substring_regex_                  = "SUBSTRING_REGEX"
	succeeds_                         = "SUCCEEDS"
	sum_                              = "SUM"
	symmetric_                        = "SYMMETRIC"
	system_time_                      = "SYSTEM_TIME"
	system_user_                      = "SYSTEM_USER"
	tablesample_                      = "TABLESAMPLE"
	time_                             = "TIME"
	timestamp_                        = "TIMESTAMP"
	timezone_hour_                    = "TIMEZONE_HOUR"
	timezone_minute_                  = "TIMEZONE_MINUTE"
	trailing_                         = "TRAILING"
	translate_                        = "TRANSLATE"
	translate_regex_                  = "TRANSLATE_REGEX"
	translation_                      = "TRANSLATION"
	treat_                            = "TREAT"
	trim_                             = "TRIM"
	trim_array_                       = "TRIM_ARRAY"
	true_                             = "TRUE"
	truncate_                         = "TRUNCATE"
	uescape_                          = "UESCAPE"
	unknown_                          = "UNKNOWN"
	unnest_                           = "UNNEST"
	upper_                            = "UPPER"
	using_                            = "USING"
	value_                            = "VALUE"
	value_of_                         = "VALUE_OF"
	varbinary_                        = "VARBINARY"
	varying_                          = "VARYING"
	var_pop_                          = "VAR_POP"
	var_samp_                         = "VAR_SAMP"
	versioning_                       = "VERSIONING"
	when_                             = "WHEN"
	width_bucket_                     = "WIDTH_BUCKET"
	window_                           = "WINDOW"
	within_                           = "WITHIN"
	without_                          = "WITHOUT"
	xml_                              = "XML"
	xmlagg_                           = "XMLAGG"
	xmlattributes_                    = "XMLATTRIBUTES"
	xmlbinary_                        = "XMLBINARY"
	xmlcast_                          = "XMLCAST"
	xmlcomment_                       = "XMLCOMMENT"
	xmlconcat_                        = "XMLCONCAT"
	xmldocument_                      = "XMLDOCUMENT"
	xmlelement_                       = "XMLELEMENT"
	xmlexists_                        = "XMLEXISTS"
	xmlforest_                        = "XMLFOREST"
	xmliterate_                       = "XMLITERATE"
	xmlnamespaces_                    = "XMLNAMESPACES"
	xmlparse_                         = "XMLPARSE"
	xmlpi_                            = "XMLPI"
	xmlquery_                         = "XMLQUERY"
	xmlserialize_                     = "XMLSERIALIZE"
	xmltable_                         = "XMLTABLE"
	xmltext_                          = "XMLTEXT"
	xmlvalidate_                      = "XMLVALIDATE"
	year_                             = "YEAR"

	// postgresql reserved words
	analyse_      = "ANALYSE"
	collation_    = "COLLATION"
	concurrently_ = "CONCURRENTLY"
	deferrable_   = "DEFERRABLE"
	do_           = "DO"
	freeze_       = "FREEZE"
	ilike_        = "ILIKE"
	initially_    = "INITIALLY"
	isnull_       = "ISNULL"
	limit_        = "LIMIT"
	notnull_      = "NOTNULL"
	placing_      = "PLACING"
	returning_    = "RETURNING"
	variadic_     = "VARIADIC"
	verbose_      = "VERBOSE"
)

func doCommand(cmd []string) (*Command, error) {

	switch cmd[0] {

	case select_, with_, from_:
		dml.ProcessSelect(cmd)

	case insert_:
		//dml.ProcessInsert(cmd)
	case update_:
		//dml.ProcessUpdate(cmd)
	case merge_, upsert_:
		//dml.ProcessMerge(cmd)
	case delete_:
		//dml.ProcessDelete(cmd)

	case commit_:
		//dml.ProcessCommit(cmd)
	case rollback_:
		//dml.ProcessRollback(cmd)
	case savepoint_:
		//dml.ProcessSavepoint(cmd)

	case set_:

	case create_:
	case alter_:
	case drop_:
	case rename_:

	case grant_:
	case revoke_:
	case comment_:

	case analyse_:
	case audit_:
	case explain_:
	case truncate_:

	}




	return nil, nil
}
